image: node:8-alpine

before_script:
  - apk add --update git curl
  - yarn global add now
  - echo "${DOTENV_STAGING}" > .env

build_backend:
  stage: build
  script:
  - cd backend
  - yarn --frozen-lockfile
  - yarn build
  artifacts:
    paths:
    - backend/node_modules/
    - backend/build/
    expire_in: 1 week

test_backend:
  stage: test
  script:
  - cd backend
  - yarn test

test_frontend:
  stage: test
  script:
  - cd frontend
  - yarn --frozen-lockfile
  - yarn lint
  artifacts:
    paths:
    - frontend/node_modules/
    expire_in: 1 week

deploy_staging:
  stage: deploy
  script:
  - cd backend
  - yarn prisma login --key="${PRISMA_CLOUD_SESSION_KEY}"
  - yarn prisma deploy
  - now --dotenv -t ${NOW_TOKEN} -T volst
  - now alias -t ${NOW_TOKEN} -T volst
  only:
    - master
  environment:
    name: staging
    url: new-food-order-staging.now.sh
