sudo: false

language:
  node_js

node_js:
  - '8'

before_install:
  - yarn global add now
  - echo "${DOTENV_STAGING}" > .env

script:
  npm run ci

jobs:
  include:
    - stage: build
      script:
        - cd backend
        - yarn --frozen-lockfile
        - yarn build
    - stage: test
      script:
        - cd backend
        - yarn test
    - stage: test
      script:
        - cd frontend
        - yarn --frozen-lockfile
        - yarn test
    - stage: deploy
        - cd backend
        - yarn prisma login --key="${PRISMA_CLOUD_SESSION_KEY}"
        - yarn prisma deploy
        - now --dotenv -t ${NOW_TOKEN} -T volst
        - now alias -t ${NOW_TOKEN} -T volst

stages:
  - name: deploy
    if: branch = master

after_success:
