sudo: false

language:
  node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules
    - frontend/build
    - backend/build
    - menu-app/build
    - menu-app/.next

before_install:
  - yarn global add now dotenv-filter-cli

jobs:
  include:
    - stage: build
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(backend/|\.travis.yml)' || exit 0
        - yarn --frozen-lockfile
        - cd backend
        - yarn build
    - stage: build
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(frontend/|\.travis.yml)' || exit 0
        - yarn --frozen-lockfile
        - cd frontend
        - yarn build
    - stage: build
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(menu-app/|\.travis.yml)' || exit 0
        - yarn --frozen-lockfile
        - cd menu-app
        - yarn build
    - stage: test
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(backend/|\.travis.yml)' || exit 0
        - cd backend
        - yarn test
    - stage: test
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(frontend/|\.travis.yml)' || exit 0
        - cd frontend
        - yarn test
    - stage: deploy
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(backend/|\.travis.yml)' || exit 0
        - cd backend
        - "mkdir -p ~/.prisma && echo \"cloudSessionKey: ${PRISMA_CLOUD_SESSION_KEY}\" > ~/.prisma/config.yml"
        - yarn prisma login
        - yarn prisma deploy --force
        - dotenv-filter --prefix=BACKEND_ > .env.now
        - now --dotenv=.env.now -t ${NOW_TOKEN} -T volst
        - now alias -t ${NOW_TOKEN} -T volst
    - stage: deploy
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(frontend/|\.travis.yml)' || exit 0
        - cd frontend
        - now -t ${NOW_TOKEN} -T volst
        - now alias -t ${NOW_TOKEN} -T volst
    - stage: deploy
      script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(menu-app/|\.travis.yml)' || exit 0
        - cd menu-app
        - now -t ${NOW_TOKEN} -T volst
        - now alias -t ${NOW_TOKEN} -T volst

stages:
  - build
  - test
  - name: deploy
    if: branch = master
