sudo: false

language:
  node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - frontend/node_modules
    - backend/build
    - backend/node_modules

before_install:
  - yarn global add now dotenv-filter-cli

jobs:
  include:
    - stage: build
      script:
        - cd backend
        - yarn --frozen-lockfile
        - yarn build
    - stage: test
      script:
        - cd backend
        - yarn test
    - stage: test
      script:
        - cd frontend
        - yarn --frozen-lockfile
        - yarn test
    - stage: deploy
      script:
        - cd backend
        - yarn prisma login --key="${PRISMA_CLOUD_SESSION_KEY}"
        - yarn prisma deploy
        - dotenv-filter --prefix=BACKEND_ > .env.now
        - now --dotenv=.env.now -t ${NOW_TOKEN} -T volst
        - now alias -t ${NOW_TOKEN} -T volst

stages:
  - build
  - test
  - name: deploy
    if: branch = master
